name: first-workflow
run-name: First Workflow
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest commit
        uses: actions/checkout@v4

      - name: Create .env file
        run: touch .env && echo "${{secrets.TEST_ENV}}" >> .env

      - name: Print .env file
        run: cat .env
